[tool.poetry]
name = "arbitrage-bot"
version = "0.1.0"
description = "A sports arbitrage betting bot"
authors = ["Your Name, youremail@example.com"]

[tool.poetry.dependencies]
python = "^3.11"
selenium = "^4.5.0"
requests = "^2.26.0"
beautifulsoup4 = "^4.10.0"
# Add other dependencies if required for your project

[tool.poetry.dev-dependencies]
pytest = "^7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

