services:
  - type: worker
    name: arbitrage-bot
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    envVars:
      - key: HEARTBEAT_INTERVAL
        value: "60"
      - key: SENDER_EMAIL
        value: "social.marketing638@gmail.com"
      - key: SENDER_PASSWORD
        value: "sbhb wscc dbua qsho"
      - key: RECEIVER_EMAIL
        value: "Ashishsharmaa2007@gmail.com"
      - key: SMTP_SERVER
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "465"
