services:
  - type: worker
    name: arbitrage-bot
    env: python
    buildCommand: "./build.sh"
    startCommand: "./start.sh"
    plan: starter
    autoDeploy: false
    envVars:
      - key: HEARTBEAT_INTERVAL
        value: "180"  # 3 minutes
      - key: SCRAPE_INTERVAL
        value: "120"  # 2 minutes
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false 
      - key: RECEIVER_EMAIL
        sync: false
      - key: SMTP_SERVER
        value: "smtp.gmail.com"
      - key: SMTP_PORT
        value: "465"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: TZ
        value: "America/Toronto"  # Set to Canadian timezone
    scaling:
      minInstances: 1
      maxInstances: 1
