services:
  - type: worker  # Worker service to avoid needing a port
    name: arbitrage-bot  # Service name
    env: python  # Python environment
    buildCommand: "poetry install --no-root"  # Install all dependencies
    startCommand: "poetry run python main.py"  # Run the bot in the Poetry environment
    envVars:
      - key: HEARTBEAT_INTERVAL
        value: "60"  # Set heartbeat interval (1 minute)
      - key: SENDER_EMAIL
        value: "social.marketing638@gmail.com"  # Replace with your email
      - key: SENDER_PASSWORD
        value: "sbhb wscc dbua qsho"  # Replace with your app password
      - key: RECEIVER_EMAIL
        value: "Ashishsharmaa2007@gmail.com"  # Replace with the receiver's email
      - key: SMTP_SERVER
        value: "smtp.gmail.com"  # SMTP server for email
      - key: SMTP_PORT
        value: "465"  # SMTP port for email
    healthCheckPath: /  # Optional: Add a health check endpoint if applicable
    plan: free  # Use the free plan for development
