services:
  - type: worker  # Worker service to avoid needing a port
    name: arbitrage-bot  # Service name
    env: python  # Python environment
    buildCommand: "poetry install --only main"  # Install dependencies
    startCommand: "python main.py"  # Command to start your bot
    envVars:
      - key: HEARTBEAT_INTERVAL
        value: "60"  # Set heartbeat interval (1 minute)
